namespace Site_Manager
{
    class GlobalString
    {
        public const string COMPOSITE_KEY_FTPCONFIG = "FileTransferProtocolConfiguration";
        public const string COMPOSITE_KEY_FTPCONFIG_USERNAME = "username";
        public const string COMPOSITE_KEY_FTPCONFIG_PASSWORD = "password";
        public const string COMPOSITE_KEY_FTPCONFIG_SERVER = "server";

        public const string COMPOSITE_KEY_COREMODULES = "CoreModules";
        public const string COMPOSITE_KEY_COREMODULES_PREFIX = "module_";

        public const string COMPOSITE_KEY_DEVOPTIONS = "DeveloperOptions";
        public const string COMPOSITE_KEY_DEVOPTIONS_BLANKDEPLOY = "blankdeploy";
        public const string COMPOSITE_KEY_DEVOPTIONS_USETESTDIRECTORY = "usetestdirectory";
        public const string COMPOSITE_KEY_DEVOPTIONS_LOCALDEPLOY = "localdeploy";

        public const string FILENAME_WEBPAGES = "webpages.json";
        public const string FILENAME_CORE_MODULES = "modules.json";

        public static string DECODE_CHEVRON_UP = System.Net.WebUtility.HtmlDecode("&#xE972;");
        public static string DECODE_CHEVRON_DOWN = System.Net.WebUtility.HtmlDecode("&#xE971;");

        public static string HTML_BUILDER_SIGNATURE = "<!-- Generated by Site Manager (https://go.egartley.net/manager) -->";
    }
}