namespace Site_Manager
{
    class HTMLBuilder
    {
        public static string GetRedirectionHTML(string destination)
        {
            Debug.Out($"Returning HTML for redirection to \"{destination}\"", "HTML BUILDER");
            return "<!DOCTYPE html><head><!-- Generated by Site Manager UWP !--><script type=\"text/javascript\">window.location=\"" + destination + "\"</script></head><body></body></html>";
        }

        public static string GetNavigationBarHTML(string active)
        {
            // lazy way to handle determining what nav item is active if any at all
            // dependent upon the inputted nav code, doesn't work without it being specifically configured
            // should probably be more dynamic in the future, but it works now, so...
            string anchor = "class=\"nav-item ", s = CoreManager.GetModuleByTag("navbar").Code, r = s.Substring(0, s.IndexOf(anchor)), o = s;

            if (o.IndexOf(active) == -1)
            {
                return o; // don't bother continuing, won't be in the nav bar
            }

            while (s.IndexOf(anchor) != -1)
            {
                s = s.Substring(s.IndexOf(anchor) + anchor.Length);
                string titleClass = s.Substring(0, s.IndexOf("\">")).ToLower();
                if (titleClass == active)
                {
                    r = o.Replace(anchor + titleClass, anchor + "active");
                    break;
                }
            }
            return r;
        }

        public static string GetFullPageHTML(ManagedWebPage page)
        {
            Debug.Out($"Returning HTML for page \"{page.Title}\" ({page.RelativeURL})", "HTML BUILDER");
            return "<!DOCTYPE html>\n<head>\n<!-- Generated by Site Manager UWP !-->\n<title>" + page.Title + " - egartley.net</title>\n" + CoreManager.GetModuleByTag("header").Code + "\n" + page.AdditionalHeaderHTML + "\n</head>\n<body>\n<div class=\"root-container\">\n<div class=\"container navbar-container\">\n" + GetNavigationBarHTML(page.Title.ToLower()) + "\n</div>\n<div class=\"container-container\">\n<div class=\"container pagecontent-container\">\n<div class=\"page-title\">\n<span>" + page.Title + "</span>\n</div\n><div class=\"page-meta\">\n<span class=\"secondary-text\">Last updated " + page.GetLastUpdatedAsString() + "</span>\n</div>\n<div class=\"page-content\">\n" + page.ContentHTML + "\n</div>\n</div>\n<div class=\"container sidebar-container\">\n" + CoreManager.GetModuleByTag("sidebar").Code + "\n</div>\n</div>\n<div class=\"container footer-container\">\n" + CoreManager.GetModuleByTag("footer").Code + "\n</div>\n</div>\n</body>\n</html>";
        }
    }
}